server:
  http_listen_port: 9009
  log_level: info

# Anneaux en mémoire pour un mode "tout-en-un"
distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1

store_gateway:
  sharding_ring:
    kvstore:
      store: inmemory

compactor:
  data_dir: /data/compactor
  sharding_ring:
    kvstore:
      store: inmemory

# Stockage blocs local (filesystem)
blocks_storage:
  backend: filesystem
  tsdb:
    dir: /data/tsdb
  bucket_store:
    sync_dir: /data/tsdb-sync

# Chemin des règles (pas de "ruler.storage")
ruler:
  rule_path: /data/rules

# Exposer un endpoint Prometheus compatible
api:
  prometheus_http_prefix: /prometheus
