auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/chunks
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    shared_store: filesystem

chunk_store_config:
  max_look_back_period: 0s

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules

limits_config:
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
