server:
  http_listen_port: 3200
  log_level: info

distributor:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

ingester:
  max_block_bytes: 1000000
  max_block_duration: 5m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

compactor:
  compaction:
    block_retention: 1h

metrics_generator:
  processor:
    service_graphs: {}
    span_metrics: {}
  storage:
    path: /var/tempo/generator
    remote_write:
      - url: http://mimir:9009/api/v1/push

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal
